kind: Secret
apiVersion: v1
metadata:
  name: emp-secret
  namespace: prod-app
data:
 SPRING.DATASOURCE.USERNAME: cm9vdA==
 SPRING.DATASOURCE.PASSWORD: TXlzcWxAMTIz
 MYSQL_ROOT_PASSWORD: TXlzcWxAMTIz

